<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_PRICE_noUi-handle noUi-handle-upper</name>
   <tag></tag>
   <elementGuidId>38926507-4ca2-4d41-93df-99b3c6b95c27</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.noUi-handle.noUi-handle-upper</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='slider']/div/div[2]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#slider div >> nth=4</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>38e5ddd5-5114-4597-9541-95a5041ea393</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>noUi-handle noUi-handle-upper</value>
      <webElementGuid>2831b61e-18ed-474f-bcf2-3b1bce7e5185</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;slider&quot;)/div[@class=&quot;noUi-base&quot;]/div[@class=&quot;noUi-origin noUi-background&quot;]/div[@class=&quot;noUi-handle noUi-handle-upper&quot;]</value>
      <webElementGuid>131438f3-766e-4e99-9152-fae6a65f72d6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='slider']/div/div[2]/div</value>
      <webElementGuid>8a337931-04a1-413d-b6de-0ceb1b647502</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[2]/div</value>
      <webElementGuid>754ed404-752d-49a2-a2a8-27b2826f5f6c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
